### ISSUE TITLE
Not all genes have a corresponding ENSG format gene ID.

### ISSUE THREAD

**Issue by ChengWan9** [manqizhou/moETM#3]
Thanks for your great work! But not all genes have a corresponding ENSG format gene ID, how to deal with it?QAQ

**Comment by manqizhou** [comment]
Hi. Among ~38000 genes, ~36000 of them have matched Ensembl ids (~5% missing). Most of the missing ones are novel genes or pseudogenes, which we did not include in the study.
If you have many genes with missing Ensembl ID in your data, you might want to check if your gene symbol are official symbols or alias symbols using the Ensemble website https://useast.ensembl.org/Homo_sapiens/Info/Index.
